### ISSUE TITLE
Board sizes 2, 3

### ISSUE THREAD

**Issue by SirMoM** [teamvilbel/NQueensProblemWithProcessingAndProlog#14]
Brett Größen von 2 und 3 erzeugen eine Exception.

```java
This has no solutions
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at thm.vilbel.com.processing.ProcessingApplication.goToBoard(ProcessingApplication.java:663)
	at thm.vilbel.com.processing.ProcessingApplication.access$2(ProcessingApplication.java:660)
	at thm.vilbel.com.processing.ProcessingApplication$15.doAction(ProcessingApplication.java:495)
	at thm.vilbel.com.processing.textfield.ProcessingTextField.keyPressed(ProcessingTextField.java:189)
	at thm.vilbel.com.processing.ProcessingApplication.keyPressed(ProcessingApplication.java:341)
	at processing.core.PApplet.keyPressed(PApplet.java:3121)
	at processing.core.PApplet.handleKeyEvent(PApplet.java:2996)
	at processing.core.PApplet.dequeueEvents(PApplet.java:2648)
	at processing.core.PApplet.handleDraw(PApplet.java:2486)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1547)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:313)
```

**Comment by SirMoM** [comment]
bidde testen

**Comment by jeanpauledoh** [comment]
Es kommt keine Exception mehr. Im MainMenu kommt die Meldung das es nicht geht und im UserInput ändert er zwar die Boardgöße, sagt aber dann beim klick auf 'Solve' das es keine Lösung gibt.
