### ISSUE TITLE
Benutzer bestimme größe für das Brett

### ISSUE THREAD

**Issue by SirMoM** [teamvilbel/NQueensProblemWithProcessingAndProlog#3]

**Comment by SirMoM** [comment]
#26
@jeanpauledoh Check mal ob das bugs hat ^^

**Comment by jeanpauledoh** [comment]
funktioniert soweit ohne probleme, dauer nur ziemlich lange bis das feld angezeigt wird

**Comment by SirMoM** [comment]
Ja bei Größen über 11 wird es echt kritisch da Prolog alle Kombinationen einfach durchtestet.
"Unser" Prolog Programm ist nicht so klug, da es dich um einen Brute-Force Vorgehensweise handelt.

**Comment by SirMoM** [comment]
@jeanpauledoh das heißt aber nich das es nicht möglich sein sollte XD
Du hast nämlich geschummelt...
```java
		this.queenPositions = new ArrayList<String>();
		this.queenPositions.add("A");
		this.queenPositions.add("B");
		this.queenPositions.add("C");
		this.queenPositions.add("D");
		this.queenPositions.add("E");
		this.queenPositions.add("F");
		this.queenPositions.add("G");
		this.queenPositions.add("H");
		this.queenPositions.add("I");
		this.queenPositions.add("J");
		this.queenPositions.add("K");
```
Das geht halt nicht da ist ja die Größe bis 11 "gehardcoded".
Die Lösung liegt in der API und das dynamische hinzufügen von Variablen,

**Comment by SirMoM** [comment]
btw das passiert wenn man 12 als größe hat
```java
distinct(n_queens(12, )), labeling([ff], ).
org.jpl7.PrologException: PrologException: error(syntax_error(cannot_start_term), string('distinct(n_queens(12, )), labeling([ff], ). ', 21))
	at org.jpl7.Query.fetchNextSolution(Query.java:437)
	at org.jpl7.Query.getSubstWithNameVars(Query.java:460)
	at org.jpl7.Util.textToTerm(Util.java:128)
	at org.jpl7.Query.<init>(Query.java:169)
	at org.jpl7.Query.hasSolution(Query.java:921)
	at thm.vilbel.com.prolog.SolutionsWithProlog.solve(SolutionsWithProlog.java:215)
	at thm.vilbel.com.processing.ProcessingApplication$6.doAction(ProcessingApplication.java:140)
	at thm.vilbel.com.processing.button.ProcessingButton.mousePressed(ProcessingButton.java:148)
	at thm.vilbel.com.processing.ProcessingApplication.mouseClicked(ProcessingApplication.java:578)
	at processing.core.PApplet.mouseClicked(PApplet.java:2874)
	at processing.core.PApplet.handleMouseEvent(PApplet.java:2754)
	at processing.core.PApplet.dequeueEvents(PApplet.java:2645)
	at processing.core.PApplet.handleDraw(PApplet.java:2486)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1547)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:313)
```

**Comment by SirMoM** [comment]
Also das bezieht sich auf das Auswählen der Größe im user input.

**Comment by jeanpauledoh** [comment]
Ok, also unabhängig davon wie groß das Spielfeld werden kann baue ich es dynamisch um.

**Comment by SirMoM** [comment]
und außerdem ist es möglich sich das Brett lösen zu lassen und dann die Größe zu ändern. Das führt zwangsläufig zu falschen Ergebnissen.

**Comment by jeanpauledoh** [comment]
Im letzten commit (https://github.com/teamvilbel/NQueensProblemWithProcessingAndProlog/commit/b7a75c44c32b95e47c96ac112e28146b9bdd6da2) hab ichs soweit angepasst das es nicht mehr direkt abstürzt wenn man 12 als Größe angibt. Sollte jetzt dynamisch genug sein um theoretisch unendliche boardgrößen zu handlen, habs aber nicht über die API gelöst da mir kein Ansatz gelungen ist.

**Comment by SirMoM** [comment]
Und die Größen Änderung nach einer Lösung?

**Comment by jeanpauledoh** [comment]
Durch die eingebaute Reset-Funktion die auch greift sobald man die Größenangabe gemacht hat, wird das Board zurückgesetzt sobald man eine Größenangabe mit Enter bestätigt auch wenn man im UserInput-Screen bereits eine Lösung hat. Oder meinst du was anderes?

**Comment by SirMoM** [comment]
ja genau hast du das getestet?

**Comment by jeanpauledoh** [comment]
Jop, funktioniert sauber
