### ISSUE TITLE
IndexOutOfBoundsException und Absturz des Programms

### ISSUE THREAD

**Issue by jeanpauledoh** [teamvilbel/NQueensProblemWithProcessingAndProlog#8]
wenn man nach dem Start des Programms direkt auf '8x8' oder '10x10' geht, zwei Solutions sich über 'Next' anzeigen lässt und dann über 'Back' und 'Start' verucht '4x4' auszuwählen gibts eine IndexOutOfBoundsException und das Programm ist tot.
Stacktrace:
java.lang.IndexOutOfBoundsException: Index: 4, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at thm.vilbel.com.processing.ProcessingApplication.goToBoard(ProcessingApplication.java:526)
	at thm.vilbel.com.processing.ProcessingApplication.access$200(ProcessingApplication.java:26)
	at thm.vilbel.com.processing.ProcessingApplication$1.doAction(ProcessingApplication.java:70)
	at thm.vilbel.com.processing.button.ProcessingButton.mousePressed(ProcessingButton.java:148)
	at thm.vilbel.com.processing.ProcessingApplication.mouseClicked(ProcessingApplication.java:432)
	at processing.core.PApplet.mouseClicked(PApplet.java:2817)
	at processing.core.PApplet.handleMouseEvent(PApplet.java:2697)
	at processing.core.PApplet.dequeueEvents(PApplet.java:2607)
	at processing.core.PApplet.handleDraw(PApplet.java:2448)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1557)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)

**Comment by SirMoM** [comment]
Ich glaube ich habs gefixed ^^ kannst ja mal drüberschauen

**Comment by jeanpauledoh** [comment]
sieht gut aus
